name: geocoder_flutter
description: Forward and reverse geocoding.
version: 0.2.3-prerelease
homepage: https://github.com/Yash-Garg/geocoder_flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.aloisdeniel.geocoder
        pluginClass: GeocoderPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  pedantic: ^1.11.0

environment:
  flutter: ">=2.0.0"
  sdk: ">=2.12.0-0 <3.0.0"
